//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupoTramite", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    [System.SerializableAttribute()]
    public partial class GrupoTramite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadMaxFuncionariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dominio.ServiceReference.Grupo GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dominio.ServiceReference.Usuario[] grupoFuncionariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadMaxFuncionarios {
            get {
                return this.CantidadMaxFuncionariosField;
            }
            set {
                if ((this.CantidadMaxFuncionariosField.Equals(value) != true)) {
                    this.CantidadMaxFuncionariosField = value;
                    this.RaisePropertyChanged("CantidadMaxFuncionarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dominio.ServiceReference.Grupo Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dominio.ServiceReference.Usuario[] grupoFuncionarios {
            get {
                return this.grupoFuncionariosField;
            }
            set {
                if ((object.ReferenceEquals(this.grupoFuncionariosField, value) != true)) {
                    this.grupoFuncionariosField = value;
                    this.RaisePropertyChanged("grupoFuncionarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupo", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    [System.SerializableAttribute()]
    public partial class Grupo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dominio.ServiceReference.Grupo RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dominio.ServiceReference.EnumPerfil TipoPerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dominio.ServiceReference.Grupo Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dominio.ServiceReference.EnumPerfil TipoPerfil {
            get {
                return this.TipoPerfilField;
            }
            set {
                if ((this.TipoPerfilField.Equals(value) != true)) {
                    this.TipoPerfilField = value;
                    this.RaisePropertyChanged("TipoPerfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumPerfil", Namespace="http://schemas.datacontract.org/2004/07/Dominio")]
    public enum EnumPerfil : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAutorizado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FuncionarioMantenimiento = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anonimo = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFAddGrupo", ReplyAction="http://tempuri.org/IService/WCFAddGrupoResponse")]
        bool WCFAddGrupo(string nombreGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFAddGrupo", ReplyAction="http://tempuri.org/IService/WCFAddGrupoResponse")]
        System.Threading.Tasks.Task<bool> WCFAddGrupoAsync(string nombreGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFAddTramite", ReplyAction="http://tempuri.org/IService/WCFAddTramiteResponse")]
        bool WCFAddTramite(string titulo, string desc, double costo, int tiempo, Dominio.ServiceReference.GrupoTramite[] gruposTramite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFAddTramite", ReplyAction="http://tempuri.org/IService/WCFAddTramiteResponse")]
        System.Threading.Tasks.Task<bool> WCFAddTramiteAsync(string titulo, string desc, double costo, int tiempo, Dominio.ServiceReference.GrupoTramite[] gruposTramite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFGuardarTxt", ReplyAction="http://tempuri.org/IService/WCFGuardarTxtResponse")]
        bool WCFGuardarTxt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFGuardarTxt", ReplyAction="http://tempuri.org/IService/WCFGuardarTxtResponse")]
        System.Threading.Tasks.Task<bool> WCFGuardarTxtAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Dominio.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Dominio.ServiceReference.IService>, Dominio.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool WCFAddGrupo(string nombreGrupo) {
            return base.Channel.WCFAddGrupo(nombreGrupo);
        }
        
        public System.Threading.Tasks.Task<bool> WCFAddGrupoAsync(string nombreGrupo) {
            return base.Channel.WCFAddGrupoAsync(nombreGrupo);
        }
        
        public bool WCFAddTramite(string titulo, string desc, double costo, int tiempo, Dominio.ServiceReference.GrupoTramite[] gruposTramite) {
            return base.Channel.WCFAddTramite(titulo, desc, costo, tiempo, gruposTramite);
        }
        
        public System.Threading.Tasks.Task<bool> WCFAddTramiteAsync(string titulo, string desc, double costo, int tiempo, Dominio.ServiceReference.GrupoTramite[] gruposTramite) {
            return base.Channel.WCFAddTramiteAsync(titulo, desc, costo, tiempo, gruposTramite);
        }
        
        public bool WCFGuardarTxt() {
            return base.Channel.WCFGuardarTxt();
        }
        
        public System.Threading.Tasks.Task<bool> WCFGuardarTxtAsync() {
            return base.Channel.WCFGuardarTxtAsync();
        }
    }
}
