//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFChangeDatosProveedor", ReplyAction="http://tempuri.org/IService/WCFChangeDatosProveedorResponse")]
        bool WCFChangeDatosProveedor(string idProveedor, System.DateTime fechaIngreso, bool esVIP, double valorArncelVIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFChangeDatosProveedor", ReplyAction="http://tempuri.org/IService/WCFChangeDatosProveedorResponse")]
        System.Threading.Tasks.Task<bool> WCFChangeDatosProveedorAsync(string idProveedor, System.DateTime fechaIngreso, bool esVIP, double valorArncelVIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFChangeArancelAnualProveedor", ReplyAction="http://tempuri.org/IService/WCFChangeArancelAnualProveedorResponse")]
        bool WCFChangeArancelAnualProveedor(int arancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFChangeArancelAnualProveedor", ReplyAction="http://tempuri.org/IService/WCFChangeArancelAnualProveedorResponse")]
        System.Threading.Tasks.Task<bool> WCFChangeArancelAnualProveedorAsync(int arancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFObtenerArancelAnualProveedor", ReplyAction="http://tempuri.org/IService/WCFObtenerArancelAnualProveedorResponse")]
        int WCFObtenerArancelAnualProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFObtenerArancelAnualProveedor", ReplyAction="http://tempuri.org/IService/WCFObtenerArancelAnualProveedorResponse")]
        System.Threading.Tasks.Task<int> WCFObtenerArancelAnualProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFDesactivarProveedor", ReplyAction="http://tempuri.org/IService/WCFDesactivarProveedorResponse")]
        bool WCFDesactivarProveedor(string rutProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFDesactivarProveedor", ReplyAction="http://tempuri.org/IService/WCFDesactivarProveedorResponse")]
        System.Threading.Tasks.Task<bool> WCFDesactivarProveedorAsync(string rutProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFGuardarTxtProveedores", ReplyAction="http://tempuri.org/IService/WCFGuardarTxtProveedoresResponse")]
        bool WCFGuardarTxtProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WCFGuardarTxtProveedores", ReplyAction="http://tempuri.org/IService/WCFGuardarTxtProveedoresResponse")]
        System.Threading.Tasks.Task<bool> WCFGuardarTxtProveedoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : InterfazWeb.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<InterfazWeb.ServiceReference1.IService>, InterfazWeb.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        
        
        public bool WCFChangeDatosProveedor(string idProveedor, System.DateTime fechaIngreso, bool esVIP, double valorArncelVIP) {
            return base.Channel.WCFChangeDatosProveedor(idProveedor, fechaIngreso, esVIP, valorArncelVIP);
        }
        
        public System.Threading.Tasks.Task<bool> WCFChangeDatosProveedorAsync(string idProveedor, System.DateTime fechaIngreso, bool esVIP, double valorArncelVIP) {
            return base.Channel.WCFChangeDatosProveedorAsync(idProveedor, fechaIngreso, esVIP, valorArncelVIP);
        }
        
        public bool WCFChangeArancelAnualProveedor(int arancel) {
            return base.Channel.WCFChangeArancelAnualProveedor(arancel);
        }
        
        public System.Threading.Tasks.Task<bool> WCFChangeArancelAnualProveedorAsync(int arancel) {
            return base.Channel.WCFChangeArancelAnualProveedorAsync(arancel);
        }
        
        public int WCFObtenerArancelAnualProveedor() {
            return base.Channel.WCFObtenerArancelAnualProveedor();
        }
        
        public System.Threading.Tasks.Task<int> WCFObtenerArancelAnualProveedorAsync() {
            return base.Channel.WCFObtenerArancelAnualProveedorAsync();
        }
        
        public bool WCFDesactivarProveedor(string rutProveedor) {
            return base.Channel.WCFDesactivarProveedor(rutProveedor);
        }
        
        public System.Threading.Tasks.Task<bool> WCFDesactivarProveedorAsync(string rutProveedor) {
            return base.Channel.WCFDesactivarProveedorAsync(rutProveedor);
        }
        
        public bool WCFGuardarTxtProveedores() {
            return base.Channel.WCFGuardarTxtProveedores();
        }
        
        public System.Threading.Tasks.Task<bool> WCFGuardarTxtProveedoresAsync() {
            return base.Channel.WCFGuardarTxtProveedoresAsync();
        }
    }
}
